// Lista de palavras de 5 letras, em maiúsculas e sem acentos.
// A palavra do dia é escolhida pela data, então todos recebem a mesma.
// Para ampliar o jogo, basta acrescentar palavras aqui (palavras que não
// tiverem exatamente 5 letras são ignoradas automaticamente).
const WORDS = `
ABRIR ACASO ACIMA ACESO ADIAR AGORA AINDA AJUDA ALTOS ALGUM ALTAR ALUNO AMADO AMIGO
ANDAR ANJOS ANTES APOIO ARROZ ASSIM ATRAS AVIAO BAIXO BALDE BANCO BANHO BARCO BEIJO
BICHO BOLSA BOTAR BRAVO BREVE BRIGA BRISA BURRO CABRA CACHO CAIXA CALDO CALMA CALOR
CAMPO CANTO CAPAZ CARGA CARNE CARRO CARTA CASAL CAUSA CEDER CENSO CERCA CERTO CESTA
CHAVE CHEFE CHEIO CHUVA CINCO CLARO CLIMA COBRA COISA COMER CONTA COPOS CORPO CORTE
COSTA COURO CRIAR CRUEL CULPA CURSO CURVA DADOS DANCA DEDOS DENTE DESDE DEVER DIZER
DOIDO DONOS DRAMA DUPLA DURAR ENTAO ENTRE ERRAR ESTAR EXAME FACIL FALAR FALTA FAROL
FAVOR FEBRE FEIRA FELIZ FERRO FESTA FICAR FILHO FINAL FIRME FOLHA FORCA FORMA FORNO
FORTE FRACO FRASE FREIO FRUTA FUGIR FUNDO FURIA GALHO GANHO GANSO GARFO GASTO GENTE
GESTO GOLPE GORDO GOSTO GRAMA GRAVE GRUPO GURIA HAVER HEROI HOMEM HONRA HORTA HOTEL
IDEIA IGUAL IRMAO JANTA JEITO JOGAR JOGOS JOVEM JUNTO JUSTO LADRA LAGOA LARGO LEGAL
LEITE LENTE LETRA LEVAR LIMAO LINDO LINHA LIVRE LIVRO LONGE LOUCO LUGAR LUTAR MACIO
MAGRO MANGA MAPAS MARCA MARCO MASSA MEDIR MEDOS MEIOS MELAO MENOS MENTE MESES METAL
METRO MILHO MOEDA MOLHO MORAR MORTE MOTOR MUITO MUNDO MURAL NADAR NAVIO NEGRO NERVO
NINHO NIVEL NOBRE NOITE NORTE NOVOS NUNCA NUVEM OBVIO OLHAR ONDAS ORDEM OSSOS OUTRO
OUVIR PADRE PAGAR PALCO PAPEL PARTE PASSO PASTA PATIO PEDIR PEDRA PEITO PEIXE PENSO
PERTO PIANO PILHA PISTA PLACA PLANO PLENO POBRE PODER POEMA PONTE PORCO PORTA POSSE
POUCO PRAIA PRATO PRAZO PRECO PRESO PRIMO PROVA PULAR QUASE QUEDA QUEPE RAIVA RAPAZ
RAPTO RAZAO REDES REGRA REINO RESTO RISCO RITMO RODAR ROUPA SABER SABOR SAIDA SALTO
SANTO SAUDE SECAR SELVA SENHA SENSO SERIE SERVO SINAL SOBRE SOCIO SOLTO SOMAR SONHO
SORTE SUAVE SUJAR SUSTO TALHO TARDE TECLA TEMPO TENDA TERMO TERRA TEXTO TIGRE TINTA
TOCAR TORRE TORTA TOTAL TRAJE TREVO TRIGO TROCA TURMA UNIAO URSOS VAGAS VALOR VAPOR
VASCO VELHO VENDA VENTO VERAO VERBO VERDE VIDRO VINHO VIRAR VISTA VIVER VOLTA ZEBRA
`.trim().split(/\s+/);
